services:
  nginx:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${APP_VERSION}
    container_name: "n${IMAGE_NAME}_${APP_VERSION}"
    ports:
      - 80:80
    networks:
      - dipesh-net
networks:
  dipesh-net:

#HAAHAHAHAHAHA Volume was the cause of no changes being seen i guess let me test it once again