services:
  nginx:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${APP_VERSION}
    container_name: "n${IMAGE_NAME}_${APP_VERSION}"
    ports:
      - 80:80
    volumes:
      - node_volume:/usr/share/nginx/html/
    networks:
      - dipesh-net
networks:
  dipesh-net:
volumes:
  node_volume:
